#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules/svelte-check/bin/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules/svelte-check/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules/svelte-check/bin/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules/svelte-check/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/svelte-check@3.6.9_postcss-load-config@4.0.2_postcss@8.4.38__postcss@8.4.38_svelte@4.2.15/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../svelte-check/bin/svelte-check" "$@"
else
  exec node  "$basedir/../svelte-check/bin/svelte-check" "$@"
fi
