#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules/@sveltejs/kit/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules/@sveltejs/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules/@sveltejs/kit/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules/@sveltejs/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/@sveltejs+kit@2.5.6_@sveltejs+vite-plugin-svelte@3.1.0_svelte@4.2.15_vite@5.2.10_@types+node@_ik2l6ssdztnudtmko2fnr23sa4/node_modules:/mnt/c/prj/Websites/bll.li/bll.li/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../@sveltejs/kit/svelte-kit.js" "$@"
else
  exec node  "$basedir/../@sveltejs/kit/svelte-kit.js" "$@"
fi
